language: python
sudo: false
install:
  - pip install coveralls
  - coverage run --source=mypkg main.py test
  - coveralls
script: python main.py < testing.txt
matrix:
  include:
    - python: 2.7
      env: TOXENV=py
    - python: 3.6
      env: TOXENV=py
    - python: 3.5
      env: TOXENV=py
    - python: 3.4
      env: TOXENV=py
    - python: nightly
      env: TOXENV=py
    - os: osx
      language: python
      env: TOXENV=py
  allow_failures:
    - python: nightly
      env: TOXENV=py
    - os: osx
      language: generic
      env: TOXENV=py
  fast_finish: true
branches:
  only:
    - master
notifications:
  email: false
